apiVersion: kube-ctf.downunderctf.com/v1
kind: IsolatedChallenge
metadata:
  name: no-quotes
spec:
  expires: 600
  available_at: 1600000000 # 1736553600
  type: web
  template: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: "ctf-{{ deployment_id }}"
      namespace: kubectf-challenges-isolated
      labels:
        kube-ctf.downunderctf.com/type: web
        kube-ctf.downunderctf.com/name: no-quotes
        isolated-challenge.kube-ctf.downunderctf.com/deployment: "{{ deployment_id }}"
        isolated-challenge.kube-ctf.downunderctf.com/owner: "{{ owner_id }}"
      annotations:
        janitor/expires: "{{ expires }}"
    spec:
      replicas: 1
      selector:
        matchLabels:
          isolated-challenge.kube-ctf.downunderctf.com/deployment: "{{ deployment_id }}"
          isolated-challenge.kube-ctf.downunderctf.com/owner: "{{ owner_id }}"
      template:
        metadata:
          labels:
            role: web
            kube-ctf.downunderctf.com/type: web
            kube-ctf.downunderctf.com/name: no-quotes
            isolated-challenge.kube-ctf.downunderctf.com/deployment: "{{ deployment_id }}"
            isolated-challenge.kube-ctf.downunderctf.com/owner: "{{ owner_id }}"
        spec:
          enableServiceLinks: false
          automountServiceAccountToken: false
          containers:
          - name: web
            image: us-east1-docker.pkg.dev/ctfd-uoftctf-2026/chals/no-quotes:latest
            resources:
              limits:
                cpu: 80m
                memory: 256Mi
              requests:
                cpu: 40m
                memory: 128Mi
            ports:
             - containerPort: 5000
               name: port-5000

    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: "ctf-{{ deployment_id }}"
      namespace: kubectf-challenges-isolated
      labels:
        kube-ctf.downunderctf.com/type: web
        kube-ctf.downunderctf.com/name: no-quotes
        isolated-challenge.kube-ctf.downunderctf.com/deployment: "{{ deployment_id }}"
        isolated-challenge.kube-ctf.downunderctf.com/owner: "{{ owner_id }}"
      annotations:
        janitor/expires: "{{ expires }}"
    spec:
      selector:
        role: web
        isolated-challenge.kube-ctf.downunderctf.com/deployment: "{{ deployment_id }}"
      ports:
        - port: 5000
          name: port-5000
    ---
    apiVersion: traefik.containo.us/v1alpha1
    kind: IngressRoute
    metadata:
      name: ingress-ctf-{{ deployment_id }}
      namespace: kubectf-challenges-isolated
      labels:
        kube-ctf.downunderctf.com/type: web
        kube-ctf.downunderctf.com/name: no-quotes
        isolated-challenge.kube-ctf.downunderctf.com/deployment: "{{ deployment_id }}"
        isolated-challenge.kube-ctf.downunderctf.com/owner: "{{ owner_id }}"
      annotations:
        janitor/expires: "{{ expires }}"
    spec:
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: default
      routes:
        - match: Host(`{{ deployment_id }}.{{ domain }}`)
          kind: Rule
          priority: 10
          middlewares:
          - name: secure-headers
          services:
          - name: ctf-{{ deployment_id }}
            port: 5000
